#
set(_TARGET x86_64-unknown-linux-gnu)

set(LLVM_ENABLE_LIBEDIT OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBPFM  OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")
set(LLVM_ENABLE_ZLIB    OFF CACHE BOOL "")
set(LLVM_ENABLE_ZSTD    OFF CACHE BOOL "")

set(LLVM_BUILTIN_TARGETS ${_TARGET} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${_TARGET} CACHE STRING "")

set(BUILTINS_${_TARGET}_CMAKE_SYSTEM_NAME Linux CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_SYSTEM_NAME Linux CACHE STRING "")

set(BUILTINS_${_TARGET}_CMAKE_C_FLAGS   "--target=${_TARGET}" CACHE STRING "")
set(BUILTINS_${_TARGET}_CMAKE_CXX_FLAGS "--target=${_TARGET}" CACHE STRING "")
set(BUILTINS_${_TARGET}_CMAKE_ASM_FLAGS "--target=${_TARGET}" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_C_FLAGS   "--target=${_TARGET}" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_CXX_FLAGS "--target=${_TARGET}" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_ASM_FLAGS "--target=${_TARGET}" CACHE STRING "")

set(BUILTINS_${_TARGET}_CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld" CACHE STRING "")
set(BUILTINS_${_TARGET}_CMAKE_MODULE_LINKER_FLAGS "-fuse-ld=lld" CACHE STRING "")
set(BUILTINS_${_TARGET}_CMAKE_EXE_LINKER_FLAG     "-fuse-ld=lld" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_MODULE_LINKER_FLAGS "-fuse-ld=lld" CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_EXE_LINKER_FLAGS    "-fuse-ld=lld" CACHE STRING "")

set(RUNTIMES_${_TARGET}_COMPILER_RT_CXX_LIBRARY "libcxx" CACHE STRING "")

set(RUNTIMES_${_TARGET}_LIBUNWIND_USE_COMPILER_RT     ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_LIBCXXABI_USE_COMPILER_RT     ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_LIBCXXABI_USE_LLVM_UNWINDER   ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_LIBCXX_USE_COMPILER_RT        ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_COMPILER_RT_USE_LLVM_UNWINDER ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_COMPILER_RT_USE_LIBCXX        ON CACHE BOOL "")
