#
set(_SYSROOT /toolchain)
set(_TARGET x86_64-unknown-linux-musl)

set(CMAKE_INSTALL_PREFIX /toolchain/usr CACHE STRING "")

set(CLANG_ENABLE_BOOTSTRAP ON CACHE BOOL "")
set(CLANG_BOOTSTRAP_CMAKE_ARGS -D CLANG_ENABLE_BOOTSTRAP=OFF -C /musl-minimal.cmake CACHE STRING "")

set(                    CMAKE_SYSROOT ${_SYSROOT} CACHE STRING "")
set(RUNTIMES_${_TARGET}_CMAKE_SYSROOT ${_SYSROOT} CACHE STRING "")
set(BUILTINS_${_TARGET}_CMAKE_SYSROOT ${_SYSROOT} CACHE STRING "")

set(LLVM_ENABLE_LIBEDIT OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBPFM  OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")
set(LLVM_ENABLE_ZLIB    OFF CACHE BOOL "")
set(LLVM_ENABLE_ZSTD    OFF CACHE BOOL "")

set(                    LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
set(RUNTIMES_${_TARGET}_LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
set(BUILTINS_${_TARGET}_LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")

#set(RUNTIMES_${_TARGET}_COMPILER_RT_BUILD_BUILTINS    ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_COMPILER_RT_CXX_LIBRARY "libcxx" CACHE STRING "")
#set(RUNTIMES_${_TARGET}_COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_LIBUNWIND_USE_COMPILER_RT     ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_LIBCXXABI_USE_COMPILER_RT     ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_LIBCXXABI_USE_LLVM_UNWINDER   ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_LIBCXX_USE_COMPILER_RT        ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_COMPILER_RT_USE_LLVM_UNWINDER ON  CACHE BOOL "")
#set(RUNTIMES_${_TARGET}_COMPILER_RT_USE_LIBCXX        ON  CACHE BOOL "")

set(LLVM_BUILTIN_TARGETS ${_TARGET} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${_TARGET} CACHE STRING "")
