# glibc-base
set(LLVM_HOST_TRIPLE     ${GLIBC_TRIPLE} CACHE STRING "")
set(LLVM_BUILTIN_TARGETS ${GLIBC_TRIPLE} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${GLIBC_TRIPLE} CACHE STRING "")

# Statically link as much as possible to detach from the host toolchain.
set(LLVM_STATIC_LINK_CXX_STDLIB ON CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_COMPILER_RT_ENABLE_STATIC_UNWINDER ON  CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_COMPILER_RT_STATIC_CXX_STDLIB      ON  CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBCXXABI_ENABLE_STATIC_UNWINDER   ON  CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBCXX_ENABLE_STATIC_ABI_LIBRARY   ON  CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBUNWIND_ENABLE_SHARED            OFF CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBCXXABI_ENABLE_SHARED            OFF CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBCXX_ENABLE_SHARED               OFF CACHE BOOL "")
set(RUNTIMES_${GLIBC_TRIPLE}_LIBCXXABI_INSTALL_LIBRARY          OFF CACHE BOOL "")
