# syntax=docker/dockerfile:1
ARG FROM=localhost/phase0:latest

FROM ${FROM} AS phase1

# steal ca-certs from curl image for cargo to use
COPY --from=docker.io/curlimages/curl:latest /etc/ssl /etc/ssl

# This should be unneeded but we would have to patch rust search paths to look
# under /toolchain to be a proper patch. Use sysroots to ensure it will find our
# include and lib directories properly.
#ENV   CFLAGS="--sysroot=${PHASE1_SYSROOT}"
#ENV CXXFLAGS="--sysroot=${PHASE1_SYSROOT}"
#ENV  LDFLAGS="--sysroot=${PHASE1_SYSROOT}"


WORKDIR /git_sources/sccache
RUN --mount=type=cache,target=${CARGO_HOME},id=cargo \
    --mount=type=cache,target=${SCCACHE_DIR},id=sccache-phase1 \
    cargo install --root ${PHASE1_SYSROOT}/usr --path ./ --features native-zlib

WORKDIR /git_sources/coreutils
RUN --mount=type=cache,target=${CARGO_HOME},id=cargo \
    --mount=type=cache,target=${SCCACHE_DIR},id=sccache-phase1 \
    cargo install --root ${PHASE1_SYSROOT}/usr --path ./ --features unix

WORKDIR /git_sources/findutils
RUN --mount=type=cache,target=${CARGO_HOME},id=cargo \
    --mount=type=cache,target=${SCCACHE_DIR},id=sccache-phase1 \
    cargo install --root ${PHASE1_SYSROOT}/usr --path ./

WORKDIR /git_sources/diffutils
RUN --mount=type=cache,target=${CARGO_HOME},id=cargo \
    --mount=type=cache,target=${SCCACHE_DIR},id=sccache-phase1 \
    cargo install --root ${PHASE1_SYSROOT}/usr --path ./

# ###
# # GNU tools
# WORKDIR /sources/make
# RUN ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#     && make -j64 \
#     && make install
# 
# WORKDIR /sources/gawk
# RUN ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#         --disable-extensions \
#     && make -j64 \
#     && make install
# 
# WORKDIR /sources/grep
# RUN ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#     && make -j64 \
#     && make install
# 
# WORKDIR /sources/sed
# RUN ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#     && make -j64 \
#     && make install
# 
# # TODO: Drop this once all sources exist in the git mirror. Use git apply after
# WORKDIR /sources/patch
# RUN ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#     && make -j64 \
#     && make install
# 
# # We need a shell. It is not optional if we want to keep building in a container
# WORKDIR /sources/bash
# COPY bash-fix-missing-header.patch /
# RUN patch -p1 < /bash-fix-missing-header.patch && \
#     ./configure \
#         --prefix=${PHASE1_SYSROOT}/usr \
#         --build=${TRIPLE} \
#         --host=${TRIPLE} \
#         --without-bash-malloc \
#     && make -j64 \
#     && make install
# RUN ln -sv bash ${PHASE1_SYSROOT}/usr/bin/sh
# # END GNU tools
# ###
# 
# WORKDIR /sources/perl
# RUN export BUILD_ZLIB=False BUILD_BZIP2=0 \
#     && sh Configure -des \
#         -D libc=__REPLACE_LIBDIR__/${TRIPLE}/libc.so \
#         -D prefix=__REPLACE_PREFIX__ \
#         -D vendorprefix=__REPLACE_PREFIX__ \
#         -D bin=__REPLACE_PREFIX__/bin \
#         -D vendorbin=__REPLACE_PREFIX__/bin \
#         -D vendorscript=__REPLACE_PREFIX__/bin \
#         -D privlib=__REPLACE_LIBDIR__/perl5/5.40/core_perl \
#         -D archlib=__REPLACE_LIBDIR__/perl5/5.40/core_perl \
#         -D sitelib=__REPLACE_LIBDIR__/perl5/5.40/site_perl \
#         -D sitearch=__REPLACE_LIBDIR__/perl5/5.40/site_perl \
#         -D vendorlib=__REPLACE_LIBDIR__/perl5/5.40/vendor_perl \
#         -D vendorarch=__REPLACE_LIBDIR__/perl5/5.40/vendor_perl \
#         -D userelocatableinc \
#         -D useshrplib \
#         -D usethreads \
#     && sed -i \
#            -e 's|__REPLACE_PREFIX__|'${PHASE1_SYSROOT}'/usr|g' \
#            -e 's|__REPLACE_LIBDIR__|'${PHASE1_SYSROOT}'/usr/lib|g' \
#            Makefile \
#     && sed -i \
#            -e '/^[^=]*install[^=]*=/ s|__REPLACE_PREFIX__|'${PHASE1_SYSROOT}'/usr|g' \
#            -e '/^[^=]*install[^=]*=/ s|__REPLACE_LIBDIR__|'${PHASE1_SYSROOT}'/usr/lib|g' \
#            Policy.sh \
#            config.sh \
#     && sed -i \
#            -e 's|__REPLACE_PREFIX__|.../..|g' \
#            -e 's|__REPLACE_LIBDIR__|.../../lib|g' \
#            config.sh \
#            Policy.sh \
#     && make -j64 \
#     && make install
# 
# WORKDIR /sources/cmake
# RUN cmake \
#         -B build \
#         -D CMAKE_INSTALL_PREFIX=${PHASE1_SYSROOT}/usr \
#     && cmake --build build --parallel 64 \
#     && cmake --build build --target install
# 
# WORKDIR /sources/ninja
# RUN cmake \
#         -B build \
#         -D CMAKE_INSTALL_PREFIX=${PHASE1_SYSROOT}/usr \
#         -D BUILD_TESTING=OFF \
#     && cmake --build build --parallel 64 \
#     && cmake --build build --target install

# container image compat hack
RUN mkdir -p /compat/hack /compat/bin /compat/tmp \
    && ln -sfv ${PHASE1_SYSROOT} /compat/hack/toolchain \
    && ln -sfv ${PHASE1_SYSROOT}/usr/bin/sh /compat/bin/sh

FROM scratch
COPY --from=phase1 /sysroots/phase1 /sysroots/phase1
COPY --from=phase1 /compat/hack/ /
COPY --from=phase1 /compat/bin /bin
COPY --from=phase1 /compat/tmp /tmp
ENV PATH="/toolchain/usr/bin"
