# musl base config options
set(LLVM_HOST_TRIPLE     ${MUSL_TRIPLE} CACHE STRING "")
set(LLVM_BUILTIN_TARGETS ${MUSL_TRIPLE} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${MUSL_TRIPLE} CACHE STRING "")
set(RUNTIMES_${MUSL_TRIPLE}_LIBCXX_HAS_MUSL_LIBC ON CACHE BOOL "")
