profile = 'dist'

[llvm]
# This needs to be set even when using llvm-config in a specific target. If
# this is missing, it will still attempt to link against libstdc++
use-libcxx = true

# TODO: Not sure I need to keep this activated since I am reusing the system
#       llvm build (in /opt/build)
download-ci-llvm = false
cflags = '--sysroot=${MUSL_SYSROOT}'
cxxflags = '--sysroot=${MUSL_SYSROOT}'
ldflags = '--sysroot=${MUSL_SYSROOT}'

[build]
build = '${MUSL_TRIPLE}'
host = ['${MUSL_TRIPLE}']
target = ['${MUSL_TRIPLE}']

bootstrap-cache-path = '/rustbootstrapdeps'
#rustc-wrapper = "sccache"
docs = false
extended = false

[install]
prefix = '${MUSL_SYSROOT}/usr'
sysconfdir = 'etc'

[rust]
llvm-libunwind = 'system'

# TODO: This is only for the initial compilation. All tooling is linked against
#       musl libc sysroot, but we will be rebuilding rust once more and these
#       add significant time to the first build.
lto = 'off'
debug = false
optimize = false

[target.${MUSL_TRIPLE}]
# Use the build directory from the previous clang build
llvm-config = '/opt/build/tools/clang/stage2-bins/bin/llvm-config'

# Rust defaults to `crt-static = true` on musl
# https://github.com/rust-lang/rust/issues/103199
crt-static = false

[dist]
