set(TRIPLE "x86_64-unknown-linux-musl" CACHE STRING "")

set(CMAKE_BUILD_TYPE      "Release"   CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD "X86"       CACHE STRING "")
set(LLVM_ENABLE_PROJECTS  "clang;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES  "libunwind;libcxxabi;libcxx;compiler-rt" CACHE STRING "")

# Set compiler defaults
set(CLANG_DEFAULT_CXX_STDLIB "libc++"      CACHE STRING "")
set(CLANG_DEFAULT_LINKER     "lld"         CACHE STRING "")
set(CLANG_DEFAULT_RTLIB      "compiler-rt" CACHE STRING "")
set(CLANG_DEFAULT_UNWINDLIB  "libunwind"   CACHE STRING "")

# Recommended option for build performance (why is it not default?)
set(LLVM_OPTIMIZED_TABLEGEN ON CACHE BOOL "")

set(COMPILER_RT_DEFAULT_TARGET_ONLY    OFF CACHE BOOL "")
set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR ON  CACHE BOOL "")
set(LLVM_USE_RELATIVE_PATHS_IN_FILES   ON  CACHE BOOL "")
set(LLVM_INSTALL_BINUTILS_SYMLINKS     ON  CACHE BOOL "")
set(LLVM_INSTALL_CCTOOLS_SYMLINKS      ON  CACHE BOOL "")
set(LLVM_INSTALL_UTILS                 ON  CACHE BOOL "")

set(LLVM_BUILTIN_TARGETS ${TRIPLE} CACHE STRING "")
set(LLVM_RUNTIME_TARGETS ${TRIPLE} CACHE STRING "")
set(LLVM_HOST_TRIPLE     ${TRIPLE} CACHE STRING "")

set(RUNTIMES_${TRIPLE}_COMPILER_RT_USE_BUILTINS_LIBRARY ON CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_COMPILER_RT_USE_LLVM_UNWINDER    ON CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_LIBCXXABI_USE_COMPILER_RT        ON CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_LIBCXX_HAS_MUSL_LIBC             ON CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_LIBCXX_USE_COMPILER_RT           ON CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_LIBUNWIND_USE_COMPILER_RT        ON CACHE BOOL "")

# Need to disable these for musl build (TODO: revisit this)
set(LLVM_INCLUDE_TESTS           OFF CACHE BOOL "")
set(CLANG_ENABLE_ARCMT           OFF CACHE BOOL "")
set(CLANG_ENABLE_STATIC_ANALYZER OFF CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_COMPILER_RT_BUILD_GWP_ASAN OFF CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_COMPILER_RT_BUILD_MEMPROF  OFF CACHE BOOL "")
set(RUNTIMES_${TRIPLE}_COMPILER_RT_BUILD_ORC      OFF CACHE BOOL "")
